version: '3.4'

services:
  weatherntfy:
    image: weatherntfy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5823:5823
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "main.js"]
