version: '3.4'

services:
  weatherntfy:
    image: weatherntfy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5823:5823
